config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :profiles do
    resources :comments
    resources :publiccomments

    member do
      post :favorite
      get :all_favorites
    end

  end

  resources :skills do
    member do
      post :like
    end
  end

  namespace :admin do
    root "skills#about"

    resources :users
    resources :categories
    resources :comments
    resources :locations
    resources :pictures
    resources :publiccomments
    resources :profiles
    resources :skills
  end

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :skills # ApiV1::SkillsController
    resources :locations
    resources :comments
    resources :categories

    get "/comments/:id/last_comments" => "comments#last_comments"
    get "/profiles" => "profiles#index"
    post "/profiles/:id/favorite" => "profiles#favorite"
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'welcome#index'

end

app/models/admin/skill.rb
class Admin::Skill < Skill
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
  belongs_to :location

  has_many :profile_categoryships, dependent: :destroy
  has_many :categories, through: :profile_categoryships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :publiccomments, dependent: :destroy
  # Favorited by users
  has_many :user_profile_favoriteships, dependent: :destroy
  has_many :favorited_users, through: :user_profile_favoriteships, source: :user, dependent: :destroy

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/default/missing.jpg",
                    :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :s3_host_name => "s3-ap-northeast-1.amazonaws.com"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :username

  def photo_url
    if self.photo_updated_at
      self.photo.url
    else
      self.fb_image
    end
  end

end

app/models/skill.rb
class Skill < ActiveRecord::Base

  belongs_to :user

  has_many :skill_categoryships, dependent: :destroy
  has_many :categories, through: :skill_categoryships, dependent: :destroy

  # Liked by users
  has_many :user_skill_likeships, dependent: :destroy
  has_many :liked_users, through: :user_skill_likeships, source: :user, dependent: :destroy

  has_many :pictures, :dependent => :destroy

  validates_presence_of :name, :requirement, :description

  default_scope { order(updated_at: :desc) }

  def self.find_followed_skill_ids(category_ids)
    self.joins(:skill_categoryships).where(:skill_categoryships => {:category_id => category_ids}).pluck(:id).uniq
  end

  def like_by_user?(u)
    user_skill_likeships.select{ |x| x.user_id == u.id }.any?
  end

end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
  before_action :set_admin_skill, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"
  # GET /admin/skills
  # GET /admin/skills.json
  def index
    @admin_skills = Admin::Skill.all
  end

  # GET /admin/skills/1
  # GET /admin/skills/1.json
  def show
  end

  # GET /admin/skills/new
  def new
    @admin_skill = Admin::Skill.new
  end

  # GET /admin/skills/1/edit
  def edit
  end

  # POST /admin/skills
  # POST /admin/skills.json
  def create
    @admin_skill = Admin::Skill.new(admin_skill_params)

    respond_to do |format|
      if @admin_skill.save
        format.html { redirect_to @admin_skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @admin_skill }
      else
        format.html { render :new }
        format.json { render json: @admin_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/skills/1
  # PATCH/PUT /admin/skills/1.json
  def update
    if params[:destroy_image] == "1"
      @admin_skill.pictures.delete_all
    end

    respond_to do |format|
      if @admin_skill.update(admin_skill_params)
        if params[:images]
          params[:images].each { |image|
            @admin_skill.pictures.create(image: image)
          }
        end
        format.html { redirect_to @admin_skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_skill }
      else
        format.html { render :edit }
        format.json { render json: @admin_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/skills/1
  # DELETE /admin/skills/1.json
  def destroy
    @admin_skill.destroy
    respond_to do |format|
      format.html { redirect_to admin_skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def about
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_skill
    @admin_skill = Admin::Skill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_skill_params
    params.require(:admin_skill).permit(:name, :requirement, :description, :pictures, category_ids: [])
  end
end

app/controllers/api_v1/skills_controller.rb
class ApiV1::SkillsController < ApiController

  before_action :authenticate_user_from_token!, :except => [:index]
  before_action :set_user, :except => [:index]

  def index
    @skills = Skill.all
  end

  def create
    @skill = @user.skills.new(skill_params)

    if @skill.save
      if params[:images]
        params[:images].each { |image|
          @skill.pictures.create(image: image)
        }
      end
      render :json => { :message => "Successfully created", :id => @skill.id }
    else
      render :json => { :message => "Validate failed" }, :status => 400
    end
  end

  def skill_params
    params.permit(:name, :requirement, :description, :pictures, category_ids: [])
  end

  def set_user
    @user = User.find_by_authentication_token( params[:auth_token] )
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_my_skill, :only => [:edit, :update, :destroy]

  def index
    @q = Skill.ransack(params[:q])

    if params[:q]
      @skills = @q.result.includes(:categories).uniq
    else
      @skills = Skill.includes(:pictures, :user => { :profile => :location } ).all

      if current_user && current_user.profile.try(:categories)
        @skills = @skills.includes(:user_skill_likeships)

        category_ids = current_user.profile.category_ids
        followed_skill_ids = Skill.find_followed_skill_ids(category_ids)

        @unfollowed_skills = @skills.select{ |x| !followed_skill_ids.include?(x.id) }
        @skills = @skills.select{ |x| followed_skill_ids.include?(x.id) }
      end
    end

  end

  def new
    @skill = Skill.new
  end

  def show
    @skill = Skill.includes(:pictures).find(params[:id])
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    if @skill.save
      if params[:images]
        params[:images].each { |image|
          @skill.pictures.create(image: image)
        }
      end
      flash[:notice] = "技能新增成功！"
      redirect_to skill_path(@skill)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:destroy_image] == "1"
      @skill.pictures.delete_all
    end

    if @skill.update(skill_params)
      if params[:images]
        params[:images].each { |image|
          @skill.pictures.create(image: image)
        }
      end
      flash[:notice] = "技能更新成功！"
      redirect_to skill_path(@skill)
    else
      render 'edit'
    end

  end

  def destroy
    if @skill.destroy
      flash[:notice] = "技能刪除成功！"

      redirect_to :back
    end
  end

  # Add and remove like skills
  # for current_user
  def like
    @skill = Skill.find(params[:id])
    current_user.toggle_like(@skill)

    respond_to do |format|
      format.html {
        redirect_to :back
      }
      format.js
    end
  end

  private

  def set_my_skill
    @skill = current_user.skills.includes(:pictures).find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:name, :requirement, :description, :pictures, category_ids: [])
  end

end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper
end

app/helpers/api_v1/skills_helper.rb
module ApiV1::SkillsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/admin/skills/_form.html.erb
<%= form_for @admin_skill, :html => { :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :name, "技能名稱：" %><br>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>


  <div class="form-group">
    <%= f.label :name, "分類：" %><br>
    <%= f.select :category_ids, Category.all.map{ |x| [x.name, x.id] }, {}, :multiple => true, required: true %>
  </div>

  <div class="form-group">
    <%= f.label :requirement, "需自備的工具或軟體：" %><br>
    <%= f.text_area :requirement, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description, "詳細敘述自己的技能吧！" %><br>
    <%= f.text_area :description, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :pictures, '可選擇多個檔案上傳', :class => 'control-label' %><br>
    <%= file_field_tag "images[]", type: :file, multiple: true %>
    <% if @admin_skill.pictures.exists? %>
      <%= check_box_tag "destroy_image", "1" %> 刪除圖片重新上傳
    <% end %>
  </div>


  <p>
    <%= f.submit '更新', class: "btn btn-default" %>
  </p>

<% end %>

app/views/admin/skills/about.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Path</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <tr  class="success">
      <td colspan="2">官方設定值</td>
    </tr>
    <tr>
      <td><%= link_to '地區', admin_locations_path %></td>
      <td><%= Admin::Location.count %></td>
    </tr>
    <tr>
      <td><%= link_to '分類', admin_categories_path %></td>
      <td><%= Admin::Category.count %></td>
    </tr>
    <tr  class="danger">
      <td colspan="2">使用者資料(不可亂刪！)</td>
    </tr>
    <tr>
      <td><%= link_to '使用者', admin_users_path %></td>
      <td><%= Admin::User.count %></td>
    </tr>
    <tr>
      <td><%= link_to '使用者個人資料', admin_profiles_path %></td>
      <td><%= Admin::Profile.count %></td>
    </tr>
    <tr>
      <td><%= link_to '技能', admin_skills_path %></td>
      <td><%= Admin::Skill.count %></td>
    </tr>
    <% if false %>
    <tr>
      <td><%= link_to '悄悄話', admin_comments_path %></td>
      <td><%= Admin::Comment.count %></td>
    </tr>
    <% end %>
    <tr>
      <td><%= link_to '公開留言', admin_publiccomments_path %></td>
      <td><%= Admin::Publiccomment.count %></td>
    </tr>
    <tr>
      <td><%= link_to '技能照片', admin_pictures_path %></td>
      <td><%= Admin::Picture.count %></td>
    </tr>

  </tbody>

</table>

app/views/admin/skills/edit.html.erb
<h1>Editing Admin Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_skill %> |
<%= link_to 'Back', admin_skills_path %>

<script>
  $(document).ready(function() {
    $("#admin_skill_category_ids").select2();
  })
</script>

app/views/admin/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Skills</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Requirement</th>
      <th>Liked Users</th>
      <th>Created Time</th>
      <th>Updated Time</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_skills.each do |admin_skill| %>
      <tr>
        <td><%= admin_skill.name %></td>
        <td><%= admin_skill.description %></td>
        <td><%= admin_skill.requirement %></td>
        <td><%= admin_skill.liked_users_count %></td>
        <td><%= admin_skill.created_at %></td>
        <td><%= admin_skill.updated_at %></td>
        <td><%= link_to 'Show', admin_skill %></td>
        <td><%= link_to 'Edit', edit_admin_skill_path(admin_skill) %></td>
        <td><%= link_to 'Destroy', admin_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_admin_skill_path %>

app/views/admin/skills/new.html.erb
<h1>New Admin Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_skills_path %>

app/views/admin/skills/show.html.erb
<p id="notice"><%= notice %></p>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Requirement</th>
      <th>Liked Users</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @admin_skill.name %></td>
        <td><%= @admin_skill.description %></td>
        <td><%= @admin_skill.requirement %></td>
        <td><%= @admin_skill.liked_users_count %></td>
        <td><%= link_to 'Edit', edit_admin_skill_path(@admin_skill) %></td>
        <td><%= link_to 'Destroy', @admin_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_admin_skill_path(@admin_skill) %> |
<%= link_to 'Back', admin_skills_path %>

<div class="all-skills">
  <div class="container">
    <div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
      <div class="box">
        <div class="skill-info">
          <div class="row">
            <div class="col-sm-12">
              <h3><%= @admin_skill.name %></h3>
              <%= link_to like_skill_path(@admin_skill), method: :post, class: "btn", id: "like-#{@admin_skill.id}", remote: true do %>
                <% if current_user && current_user.like_skill?(@admin_skill) %>
                  <i class="fa fa-heart"><%= @admin_skill.liked_users.size %></i>
                <% else %>
                  <i class="fa fa-heart-o"><%= @admin_skill.liked_users.size %></i>
                <% end %>
              <% end %>
              <!-- share button code -->
              <div class="fb-share-button"
                  data-href="<%= skill_url(@admin_skill) %>"
                  data-layout="button_count">
              </div>
              <div class="skill-box-author">
                <h6 >
                  <%= link_to profile_path(@admin_skill.user.profile) do %>
                    <%= image_tag (@admin_skill.user.profile.photo.url), style: "width: 20px; display: inline; border-radius: 100%;" %>
                    <%= @admin_skill.user.profile.username %>
                  <% end %>
                </h6>
                <p>
                  <% if @admin_skill.user.profile.location %>
                    <%= @admin_skill.user.profile.location.city %>
                  <% else %>
                    ?地點？
                  <% end %>
                </p>
              </div>
              <hr>
              <h4><%= @admin_skill.description%></h4>
              <h5>需自備：<%= @admin_skill.requirement %></h5>
            </div>
          </div>
        </div>
      </div>
      <% if @admin_skill.pictures.last %>
        <% @admin_skill.pictures.each do |p| %>
        <div class="box">
          <div>
            <div class="skill-img">
            <%= link_to image_tag(p.image.url(:medium)), p.image.url(:large), :rel => "lightbox", data: {lightbox: @admin_skill.name} %>
            </div>
          </div>
        </div>
        <% end %>
      <% else %>
        無上傳圖片
      <% end %>
    </div>
  </div>
</div>