config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :profiles do
    resources :comments
    resources :publiccomments

    member do
      post :favorite
      get :all_favorites
    end

  end

  resources :skills do
    member do
      post :like
    end
  end

  namespace :admin do
    root "skills#about"

    resources :users
    resources :categories
    resources :comments
    resources :locations
    resources :pictures
    resources :publiccomments
    resources :profiles
    resources :skills
  end

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :skills # ApiV1::SkillsController
    resources :locations
    resources :comments
    resources :categories

    get "/comments/:id/last_comments" => "comments#last_comments"
    get "/profiles" => "profiles#index"
    post "/profiles/:id/favorite" => "profiles#favorite"
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'welcome#index'

end

app/models/admin/location.rb
class Admin::Location < Location
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :profiles

  validates_presence_of :city

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :set_admin_location, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"
  # GET /admin/locations
  # GET /admin/locations.json
  def index
    @admin_locations = Admin::Location.all
  end

  # GET /admin/locations/1
  # GET /admin/locations/1.json
  def show
  end

  # GET /admin/locations/new
  def new
    @admin_location = Admin::Location.new
  end

  # GET /admin/locations/1/edit
  def edit
  end

  # POST /admin/locations
  # POST /admin/locations.json
  def create
    @admin_location = Admin::Location.new(admin_location_params)

    respond_to do |format|
      if @admin_location.save
        format.html { redirect_to @admin_location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @admin_location }
      else
        format.html { render :new }
        format.json { render json: @admin_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/locations/1
  # PATCH/PUT /admin/locations/1.json
  def update
    respond_to do |format|
      if @admin_location.update(admin_location_params)
        format.html { redirect_to @admin_location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_location }
      else
        format.html { render :edit }
        format.json { render json: @admin_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/locations/1
  # DELETE /admin/locations/1.json
  def destroy
    @admin_location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_location
    @admin_location = Admin::Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_location_params
    params.require(:admin_location).permit(:city)
  end

end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= form_for(@admin_location) do |f| %>
  <% if @admin_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_location.errors.count, "error") %> prohibited this admin_location from being saved:</h2>

      <ul>
      <% @admin_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :city, "城市：" %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/locations/edit.html.erb
<h1>Editing Admin Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_location %> |
<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Locations</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>City</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_locations.each do |admin_location| %>
      <tr>
        <td><%= admin_location.city %></td>
        <td><%= link_to 'Edit', edit_admin_location_path(admin_location) %></td>
        <td><%= link_to 'Destroy', admin_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_admin_location_path %>

app/views/admin/locations/new.html.erb
<h1>New Admin Location</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_location_path(@admin_location) %> |
<%= link_to 'Back', admin_locations_path %>