config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :profiles do
    resources :comments
    resources :publiccomments

    member do
      post :favorite
      get :all_favorites
    end

  end

  resources :skills do
    member do
      post :like
    end
  end

  namespace :admin do
    root "skills#about"

    resources :users
    resources :categories
    resources :comments
    resources :locations
    resources :pictures
    resources :publiccomments
    resources :profiles
    resources :skills
  end

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :skills # ApiV1::SkillsController
    resources :locations
    resources :comments
    resources :categories

    get "/comments/:id/last_comments" => "comments#last_comments"
    get "/profiles" => "profiles#index"
    post "/profiles/:id/favorite" => "profiles#favorite"
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'welcome#index'

end

app/models/admin/profile.rb
class Admin::Profile < Profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
  belongs_to :location

  has_many :profile_categoryships, dependent: :destroy
  has_many :categories, through: :profile_categoryships, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :publiccomments, dependent: :destroy
  # Favorited by users
  has_many :user_profile_favoriteships, dependent: :destroy
  has_many :favorited_users, through: :user_profile_favoriteships, source: :user, dependent: :destroy

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/default/missing.jpg",
                    :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :s3_host_name => "s3-ap-northeast-1.amazonaws.com"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :username

  def photo_url
    if self.photo_updated_at
      self.photo.url
    else
      self.fb_image
    end
  end

end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  before_action :set_admin_profile, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"
  # GET /admin/profiles
  # GET /admin/profiles.json
  def index
    @admin_profiles = Admin::Profile.all
  end

  # GET /admin/profiles/1
  # GET /admin/profiles/1.json
  def show
  end

  # GET /admin/profiles/new
  def new
    @admin_profile = Admin::Profile.new
  end

  # GET /admin/profiles/1/edit
  def edit
  end

  # POST /admin/profiles
  # POST /admin/profiles.json
  def create
    @admin_profile = Admin::Profile.new(admin_profile_params)

    respond_to do |format|
      if @admin_profile.save
        format.html { redirect_to @admin_profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @admin_profile }
      else
        format.html { render :new }
        format.json { render json: @admin_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/profiles/1
  # PATCH/PUT /admin/profiles/1.json
  def update

    if params[:destroy_photo] == "1"
      @admin_profile.photo = nil
    end
    respond_to do |format|
      if @admin_profile.update(admin_profile_params)
        format.html { redirect_to @admin_profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_profile }
      else
        format.html { render :edit }
        format.json { render json: @admin_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/profiles/1
  # DELETE /admin/profiles/1.json
  def destroy
    @admin_profile.destroy
    respond_to do |format|
      format.html { redirect_to admin_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_profile
    @admin_profile = Admin::Profile.find(params[:id])
    @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_profile_params
    params.require(:admin_profile).permit(:username, :description, :photo, :location_id, category_ids: [])
  end
end

app/controllers/api_v1/profiles_controller.rb
class ApiV1::ProfilesController < ApiController


  def index
    @profiles = Profile.all
  end

  def favorite

    @user = User.find_by_authentication_token( params[:auth_token] )
    @profile = Profile.find(params[:favorite_id])

    if @user && @profile
      if @user.favorite_profile?(@profile)
        @user.favorite_profiles.delete(@profile)
        render :json => { :message => "Successfully removed from favorites", :id => @profile.id }
      else
        current_user.favorite_profiles << @profile
        render :json => { :message => "Successfully added to favorites", :id => @profile.id }
      end
    else
      render :json => { :message => "Validate failed" }, :status => 400
    end

  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  before_action :set_profile, :only => [:show, :favorite]
  before_action :set_my_profile, :only => [:edit, :update, :all_favorites]


  def show
    @public_comments = @profile.publiccomments.includes(:user => :profile)
  end

  def edit
    @skills = @profile.user.skills
  end

  def update

    if params[:destroy_photo] == "1"
      @profile.photo = nil
    end

    if @profile.update(profile_params)
      flash[:notice] = "個人資料修改成功！"
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  # Add and remove favorite profiles
  # for current_user
  def favorite

    current_user.toggle_favorite_profile(@profile)

    respond_to do |format|
      format.html {
        redirect_to :back
      }
      format.js
    end
  end

  def all_favorites
    @all_favorites = current_user.favorite_profiles
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def set_my_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:username, :description, :photo, :location_id, category_ids: [])
  end

end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/api_v1/profile_helper.rb
module ApiV1::ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<h2>修改個人資料</h2>
<%= form_for @admin_profile do |f| %>
  <% if @admin_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_profile.errors.count, "error") %> prohibited this admin_profile from being saved:</h2>

      <ul>
      <% @admin_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :username, "顯示名稱：" %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo, "更新大頭照：" %>
    <%= f.file_field :photo %>

    <% if @admin_profile.photo.exists? %>
      <%= check_box_tag "destroy_photo", "1" %> 回復Facebook照片
    <% end %>

  </div>

  <div class="form-group">
    <%= f.label :location_id, "偏好交換地區：" %>
    <%= f.select :location_id, Location.all.map{ |x| [x.city, x.id] } %>
  </div>

  <div class="form-group">
    <%= f.label :category_ids, "感興趣的主題：" %>
    <%= f.select :category_ids, Category.all.map{ |x| [x.name, x.id] }, {}, :multiple => true %>
   </div>

  <div class="form-group">
    <%= f.label :description, "介紹一下自己吧，越詳細才能讓大家更了解妳：" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <p>
    <%= f.submit '更新', class: "btn btn-default"%>
  </p>

<% end %>

<%= link_to '新增技能', new_skill_path, class: "btn btn-default" %>
<div class="all-skills">
  <div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
  <% @admin_profile.user.skills.each do |s| %>
  <div class="box">
    <div>
      <%= link_to skill_path(s) do %>
        <% if s.pictures.any? %>
        <div class="skill-img">
        <%= image_tag (s.pictures.last.image.url) %>
        </div>
        <% else %>
        無上傳圖片
        <% end %>
        <h5 class="skill-name"><strong><%= s.name %></strong></h5>
        <p><%= s.description %></p>
      <% end %>
    </div>
    <hr>
    <div class="row">
      <div class="col-sm-12">
        <div class="edit-btn">
          <%= link_to '更新', edit_skill_path(s), class: "glyphicon glyphicon-wrench" %>
          <%= link_to '刪除', skill_path(s), method: :delete, data: { confirm: "你確定要刪除這個技能?" }, class: "glyphicon glyphicon-trash" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/profiles/edit.html.erb
<h1>Editing Admin Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_profile %> |
<%= link_to 'Back', admin_profiles_path %>


<script>
  $(document).ready(function(){
    $("#admin_profile_category_ids").select2();
    $("#admin_profile_location_id").select2();
  })
</script>

app/views/admin/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Profiles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_profiles.each do |admin_profile| %>
      <tr>
        <td><%= admin_profile.username %></td>
        <td><%= admin_profile.description %></td>
        <td>
          <% if admin_profile.location %>
            <%= admin_profile.location.city %>
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_profile %></td>
        <td><%= link_to 'Edit', edit_admin_profile_path(admin_profile) %></td>
        <td><%= link_to 'Destroy', admin_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_admin_profile_path %>

app/views/admin/profiles/new.html.erb
<h1>New Admin Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_profiles_path %>

app/views/admin/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="profile">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="profile-main">
                <div class="row">
                  <div class="col-sm-12">
                    <div id="username">
                      <h1><%= @admin_profile.username %></h1>
                      <span>
                        <% if @admin_profile.location %>
                          <%= @admin_profile.location.city %>
                        <% end %>
                      </span>
                      <% if current_user %>
                        <%= link_to favorite_profile_path(@admin_profile), method: :post, class: "btn", id: "favorite", remote: true do %>
                          <% if current_user.favorite_profile?(@admin_profile) %>
                            <span class="btn btn-primary">取消收藏</span>
                          <% else %>
                            <span class="btn btn-default">收藏</span>
                          <% end %>
                          <span class="badge"><%= @admin_profile.favorited_users.size %></span>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="user-photo">
                      <% if @profile%>
                        <%= image_tag (@profile.photo.url(:medium)) %>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="row">
                      <div class="col-sm-12">
                        <h2>哈囉，關於我：</h2>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-4" >
                          <a href="#wanted" class="scroll">
                            <div class="skills-want hvr-pulse-grow">
                              <h3>我想學</h3>
                            </div>
                          </a>
                      </div>
                      <div class="col-xs-4">
                        <a href="#have">
                          <div class="skills-have hvr-pulse-grow">
                            <h3>我擅長</h3>
                          </div>
                        </a>
                      </div>
                      <div class="col-xs-4">
                        <a href="#comments">
                          <div class="publiccomments hvr-pulse-grow">
                            <h3>公開留言</h3>
                          </div>
                        </a>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                        <div id="about-description">
                          <p>
                            <% if @admin_profile.try(:description) %>
                              <%= simple_format(@admin_profile.description) %>
                            <% end %>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="skills-want"><h3 id="wanted">我想學</h3></div>
            <% @admin_profile.categories.each do |c| %>
              <%= c.name %>
            <% end %>
          </div>

          <div class="row">
            <div class="all-skills">
              <div class="skills-have"><h3 id="have">我擅長</h3></div>
              <div id="masonry-container" class="transitions-enabled infinite-scroll centered clearfix">
              <% @admin_profile.user.skills.each do |s| %>
              <div class="box">
                <div>
                  <%= link_to skill_path(s) do %>
                    <% if s.pictures.last %>
                      <div class="skill-img">
                      <%= image_tag (s.pictures.last.image.url) %>
                      </div>
                    <% else %>
                      無上傳圖片
                    <% end %>
                    <h5 class="skill-name"><strong><%= s.name %></strong></h5>
                    <p><%= s.description %></p>
                  <% end %>
                </div>
              </div>
              <% end %>
              </div>
            </div>
          </div>

          <div class="row">
            <% if false %>
            <div class="publiccomments"><h3 id="comments">公開留言</h3></div>
            <div id="publiccomments">
              <%= render 'publiccomments/publiccomment' %>
            </div>
            <% end %>
            <div class="row">
              <div class="col-sm-12">
                <div class="message">
                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">悄悄話</button>
                  <!-- Modal -->
                  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">想跟他說什麼呢</h4>
                        </div>
                        <div class="modal-body">
                        <%= form_for Comment.new, url: profile_comments_path(@admin_profile) do |f| %>
                          <div class="form-group">
                            <%= f.text_area :content, class: "form-control" %>
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <%= f.submit "回覆", class: "btn btn-default"%>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_admin_profile_path(@admin_profile) %> |
<%= link_to 'Back', admin_profiles_path %>