config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :profiles do
    resources :comments
    resources :publiccomments

    member do
      post :favorite
      get :all_favorites
    end

  end

  resources :skills do
    member do
      post :like
    end
  end

  namespace :admin do
    root "skills#about"

    resources :users
    resources :categories
    resources :comments
    resources :locations
    resources :pictures
    resources :publiccomments
    resources :profiles
    resources :skills
  end

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :skills # ApiV1::SkillsController
    resources :locations
    resources :comments
    resources :categories

    get "/comments/:id/last_comments" => "comments#last_comments"
    get "/profiles" => "profiles#index"
    post "/profiles/:id/favorite" => "profiles#favorite"
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'welcome#index'

end

app/models/admin/category.rb
class Admin::Category < Category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :skill_categoryships, dependent: :destroy
  has_many :skills, through: :skill_categoryships, dependent: :destroy

  has_many :profile_categoryships, dependent: :destroy
  has_many :profiles, through: :profile_categoryships, dependent: :destroy

  has_attached_file :category_icon,
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/default/missing.jpg",
                    :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :s3_host_name => "s3-ap-northeast-1.amazonaws.com"

  validates_attachment_content_type :category_icon, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"
  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @categories = Category.all
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category .save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    if params[:destroy_category_icon] == "1"
      @category.category_icon = nil
    end
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    if @category.skills.count == 0
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:alert] = "有文章的分類不能刪除！"
      redirect_to admin_categories_url
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :category_icon)
  end
end

app/controllers/api_v1/categories_controller.rb
class ApiV1::CategoriesController < ApiController
  def index
    @categories = Category.all
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/api_v1/categories_helper.rb
module ApiV1::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for @category, :url => admin_category_path(@category), method: :patch do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "分類：" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_icon, "分類icon" %>
    <%= f.file_field :category_icon %>

    <% if @category.category_icon.exists? %>
      <%= check_box_tag "destroy_category_icon", "1" %> 刪除檔案
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Categories</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Icon</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= image_tag (category.category_icon.url), style: "width: 100px; height: 100px; display: inline; border-radius: 100%;" %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Admin Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>